### PR TITLE
Fix 54

### LINKED ISSUE #54: NumPy compiler warnings on Windows
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Even fresh, minimal environments on Windows have a broken compiler toolchain, rendering them completely unusable.

This command creates a small environment:

```conda create -n aesara-test -c conda-forge python=3.9 aesara -y```

Upon `import aesara` there are lots of errors and warnings:

```
>>> import aesara
WARN: Could not locate executable g77
WARN: Could not locate executable f77
WARN: Could not locate executable ifort
WARN: Could not locate executable ifl
WARN: Could not locate executable f90
WARN: Could not locate executable DF
WARN: Could not locate executable efl
Using built-in specs.
COLLECT_GCC=C:\Users\osthege\AppData\Local\Continuum\miniconda3\envs\CARenv2\Library\mingw-w64\bin\gfortran.exe
COLLECT_LTO_WRAPPER=C:/Users/osthege/AppData/Local/Continuum/miniconda3/envs/CARenv2/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-5.3.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --with-gxx-include-dir=/mingw64/include/c++/5.3.0 --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-version-specific-runtime-libs --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev5, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 5.3.0 (Rev5, Built by MSYS2 project)
WARNING (aesara.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```

At first I thought this was just one environment, but the problem appears in all new environments I create. And I'm running out of non-broken old environments to fall back to 😬

With these broken environments, doing a posterior predictive sampling with a GP is about 100x slower than in non-broken envs.

### Installed packages

```shell
# packages in environment at C:\Users\osthege\AppData\Local\Continuum\miniconda3\envs\aesara-test:
#
# Name                    Version                   Build  Channel
aesara                    2.5.3            py39h7fcc1c2_0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cons                      0.4.5              pyhd8ed1ab_0    conda-forge
etuples                   0.3.5              pyhd8ed1ab_0    conda-forge
filelock                  3.6.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2022.0.0          h57928b3_3663    conda-forge
libblas                   3.9.0              13_win64_mkl    conda-forge
libcblas                  3.9.0              13_win64_mkl    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
liblapack                 3.9.0              13_win64_mkl    conda-forge
libpython                 2.1              py39hcbf5309_1    conda-forge
libzlib                   1.2.11            h8ffe710_1014    conda-forge
logical-unification       0.4.5              pyhd8ed1ab_0    conda-forge
m2w64-binutils            2.25.1                        5    conda-forge
m2w64-bzip2               1.0.6                         6    conda-forge
m2w64-crt-git             5.0.0.4636.2595836               2    conda-forge
m2w64-gcc                 5.3.0                         6    conda-forge
m2w64-gcc-ada             5.3.0                         6    conda-forge
m2w64-gcc-fortran         5.3.0                         6    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gcc-objc            5.3.0                         6    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-headers-git         5.0.0.4636.c0ad18a               2    conda-forge
m2w64-isl                 0.16.1                        2    conda-forge
m2w64-libiconv            1.14                          6    conda-forge
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
m2w64-make                4.1.2351.a80a8b8               2    conda-forge
m2w64-mpc                 1.0.3                         3    conda-forge
m2w64-mpfr                3.1.4                         4    conda-forge
m2w64-pkg-config          0.29.1                        2    conda-forge
m2w64-toolchain           5.3.0                         7    conda-forge
m2w64-toolchain_win-64    2.4.0                         0    conda-forge
m2w64-tools-git           5.0.0.4592.90b8472               2    conda-forge
m2w64-windows-default-manifest 6.4                           3    conda-forge
m2w64-winpthreads-git     5.0.0.4634.697f757               2    conda-forge
m2w64-zlib                1.2.8                        10    conda-forge
minikanren                1.0.3              pyhd8ed1ab_0    conda-forge
mkl                       2022.0.0           h0e2418a_796    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
numpy                     1.22.3           py39h6331f09_0    conda-forge
openssl                   3.0.2                h8ffe710_1    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
python                    3.9.12          hcf16a7b_1_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
scipy                     1.7.3            py39hc0c34ad_0    conda-forge
setuptools                61.3.0           py39hcbf5309_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.1               h8ffe710_0    conda-forge
tbb                       2021.5.0             h2d74725_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
```

### Environment info

```shell
active environment : aesara-test
    active env location : C:\Users\osthege\AppData\Local\Continuum\miniconda3\envs\aesara-test
            shell level : 1
       user config file : C:\Users\osthege\.condarc
 populated config files : C:\Users\osthege\.condarc
          conda version : 4.12.0
    conda-build version : 3.10.9
         python version : 3.7.2.final.0
       virtual packages : __cuda=11.0=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\osthege\AppData\Local\Continuum\miniconda3  (writable)
      conda av data dir : C:\Users\osthege\AppData\Local\Continuum\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\osthege\AppData\Local\Continuum\miniconda3\pkgs
                          C:\Users\osthege\.conda\pkgs
                          C:\Users\osthege\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\osthege\AppData\Local\Continuum\miniconda3\envs
                          C:\Users\osthege\.conda\envs
                          C:\Users\osthege\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.7.2 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by maresb**
Fix #54 

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by brandonwillard** [comment]
What are these changes supposed to do?

**Comment by maresb** [comment]
@brandonwillard this is unfortunately a stab in the dark. I don't really understand the problem or have any real ideas on how to fix them. Do you have any advice?

**Comment by brandonwillard** [comment]
> @brandonwillard this is unfortunately a stab in the dark. I don't really understand the problem or have any real ideas on how to fix them. Do you have any advice?

#54 has more to do with the Aesara initialization/config process, which uses the noisy `numpy.distutils.system_info.get_info` to get some build environment information.

The warnings like
```
WARN: Could not locate executable g77
WARN: Could not locate executable f77
WARN: Could not locate executable ifort
WARN: Could not locate executable ifl
WARN: Could not locate executable f90
WARN: Could not locate executable DF
WARN: Could not locate executable efl
```
emitted by that NumPy function shouldn't actually be signs of any errors, because they're referencing toolchain components that aren't relevant to Aesara.

The warning
```
WARNING (aesara.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```
is the only relevant one, but it depends on a confluence of external packages in one's Conda environment that has been known to change and/or be somewhat flaky across package versions.  

Even when a combination of packages is known to work, I recall there being some challenges with constructing a single, general recipe that covers everything (e.g. the Conda recipe spec doesn't make it easy to condition on non-trivial OS, requirement, and version combinations).

**Comment by maresb** [comment]
Ah, that's great to know! So you're saying that these warnings can be simply ignored?

I was concerned by the slowdown reported by @michaelosthege, but if I understand correctly then the slowdown was caused exclusively by the NumPy C-API error.

**Comment by brandonwillard** [comment]
> Ah, that's great to know! So you're saying that these warnings can be simply ignored?

Yes, the first set of warnings can be ignored.  It would be great if we could remove them altogether by capturing/filtering them in the Aesara initiation process, though.  Those steps are [here](https://github.com/aesara-devs/aesara/blob/c09d92b13e8534ebd89147a9db1fa6a84c4408ce/aesara/link/c/cmodule.py#L2716-L2723).

> I was concerned by the slowdown reported by @michaelosthege, but if I understand correctly then the slowdown was caused exclusively by the NumPy C-API error.

Yes, that's the most likely cause, and that's where some updates/changes to this recipe could help.  Last I tried, I was able to create a Conda environment with correctly linked BLAS libraries using [these instructions](https://aesara.readthedocs.io/en/latest/install_windows.html#install-requirements-and-optional-packages), but, as #54 implies, that might've changed (e.g. due to external package changes, or the detection code in Aesara linked above, etc.).

Otherwise, potential errors aside, would could consider adding the `m2w64-toolchain` requirement to Windows installs, as alluded to in #54.

**Comment by maresb** [comment]
> Yes, the first set of warnings can be ignored. It would be great if we could remove them altogether by capturing/filtering them in the Aesara initiation process, though. Those steps are [here](https://github.com/aesara-devs/aesara/blob/c09d92b13e8534ebd89147a9db1fa6a84c4408ce/aesara/link/c/cmodule.py#L2716-L2723).

Ah, ok, this seems like it should be straightforward to implement. I'll try to submit a quick patch.

> Yes, that's the most likely cause,

That's great to know! That should let me quickly resolve this upstream in pymc-feedstock! :smile:

In the meantime I'll try running a few more tests to see if any of those Conda packages helps...

> consider adding the m2w64-toolchain...as alluded to in https://github.com/conda-forge/aesara-feedstock/issues/54.

But @michaelosthege [says](https://github.com/conda-forge/aesara-feedstock/issues/54#issuecomment-1087257703):

> Including m2w64-toolchain doesn't help with these warnings.

I'm trying it out anyways...

**Comment by maresb** [comment]
PR which (hopefully) suppresses warnings submitted here: https://github.com/aesara-devs/aesara/pull/980

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@brandonwillard I accomplished my goal of cleaning up the downstream pymc feedstock here: https://github.com/conda-forge/pymc-feedstock/pull/42

The tests I added here are not strictly necessary, but could be quite useful for catching undesired warnings.

In case you're not interested, go ahead and close out this PR for me. Thanks!

**Comment by maresb** [comment]
Supserseded by #77

**Pull request closed without merging**
