### PR TITLE
unpin scipy

### LINKED ISSUE #69: why is scipy pinned below <1.8?
### Comment:

for example, 2.6.6: https://github.com/aesara-devs/aesara/blob/344ff6be5ccdd5f6bba3c51ceb4ca597aeba2fa4/setup.py#L49, and all later ones don't have this condition?

### PR DESCRIPTION
**Pull request by ngam**
fix #69 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Happy to put in that PR but I won't get around to it this week...

**Comment by brandonwillard** [comment]
> I think this should be merged but perhaps before merging this version we could revert to 2.6.6 and patch that before then applying this change to the current head?

Revert what?

It looks like we can (squash) and merge this now, but we can wait if something else needs to be done first.

**Comment by dhirschfeld** [comment]
An alternative, probably cleaner, way to accomplish the same thing would be to create a new `2.6.6` *branch* from the 2.6.6 commit and publish the new build with the fixed dep from that branch.

In that way you keep `main` pointing to latest version.

**Comment by dhirschfeld** [comment]
Another alternative would be to just merge this and then publish a new `pymc` build which depended on 2.7.1.

Publishing a new `pymc` version might be more work than just patching this conda-forge package though.

**Comment by twiecki** [comment]
We plan to release as soon as https://github.com/pymc-devs/pymc/pull/5849 is merged.

**Comment by dhirschfeld** [comment]
> *We plan to release as soon as https://github.com/pymc-devs/pymc/pull/5849 is merged.*

That's good enough for me, let's get this merged! :shipit:

**Comment by ngam** [comment]
@dhirschfeld no. What needs to be done is a repodata patch.

**Comment by ngam** [comment]
> 

Sorry, I haven't read the whole thread. You mean a new build of pymc or a new build of this?

**Comment by ngam** [comment]
Yes, a new build of pymc is sufficient to move forward. If there is a new build of pymc coming online, then all of this is moot as long as scipy is unpinned here fron now on.

**Comment by ngam** [comment]
Thanks everyone ❤️

**Comment by brandonwillard** [comment]
> I would checkout the [2.6.6 commit](https://github.com/conda-forge/aesara-feedstock/blame/9b3eff88033cec044cedc00155c0e1810e312e5f/recipe/meta.yaml#L37), remove the pin from there, bump the build, rerender and merge that first.

Ah, ok, you mean in _this_ repo.

**Comment by ngam** [comment]
No no no don't republish stuff from this repo, just do a repodata patch. I can do a PR for you in a few hours.

**Comment by ngam** [comment]
Your sane options are thus:
1. Wait until a new release of pymc and unpin scipy from here on
2. File a repodata patch to remove the scipy upper pin for a subset of versions #69

**Comment by ngam** [comment]
I think 2 is *the* much better solution

**Comment by ngam** [comment]
see repodata patch in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/280

**Comment by ngam** [comment]
This issue is now fixed. Except, we should also merge #71 asap otherwise this reappear later. 


```
~$ mamba install pymc

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.24.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['pymc']

conda-forge/osx-arm64                                2.6MB @   2.1MB/s  1.4s
conda-forge/noarch                                   8.4MB @   3.5MB/s  2.6s

Pinned packages:
  - python 3.9.*


Transaction

  Prefix: /Users/ngam/.Mambaforge-MacOSX-arm64/envs/py39

  Updating specs:

   - pymc
   - ca-certificates
   - certifi
   - openssl


  Package                    Version  Build               Channel                    Size
───────────────────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────────────────

  + aeppl                     0.0.31  pyhd8ed1ab_0        conda-forge/noarch         41kB
  + aesara                     2.6.6  py39h28ced28_0      conda-forge/osx-arm64       2MB
  + arviz                     0.12.1  pyhd8ed1ab_0        conda-forge/noarch          1MB
  + c-compiler                 1.4.2  h50ab0ce_0          conda-forge/osx-arm64       5kB
  + cctools                  973.0.1  h43ef6ec_10         conda-forge/osx-arm64      18kB
  + cctools_osx-arm64        973.0.1  h8e51184_10         conda-forge/osx-arm64       2MB
  + clang                     13.0.1  hce30654_0          conda-forge/osx-arm64     128kB
  + clang-13                  13.0.1  default_h2cfa9b4_0  conda-forge/osx-arm64       1MB
  + clang_osx-arm64           13.0.1  hc97ff27_2          conda-forge/osx-arm64      17kB
  + clangxx                   13.0.1  default_hf584372_0  conda-forge/osx-arm64     128kB
  + clangxx_osx-arm64         13.0.1  h15d2725_2          conda-forge/osx-arm64      16kB
  + cloudpickle                2.1.0  pyhd8ed1ab_0        conda-forge/noarch         25kB
  + compiler-rt               13.0.1  h94c6b0c_0          conda-forge/osx-arm64      83kB
  + compiler-rt_osx-arm64     13.0.1  h44bac85_0          conda-forge/noarch          6MB
  + cons                       0.4.5  pyhd8ed1ab_0        conda-forge/noarch         13kB
  + cxx-compiler               1.4.2  hf86a087_0          conda-forge/osx-arm64       5kB
  + etuples                    0.3.5  pyhd8ed1ab_0        conda-forge/noarch         16kB
  + fastprogress               1.0.2  pyhd8ed1ab_0        conda-forge/noarch         16kB
  + ld64                         609  h954701c_10         conda-forge/osx-arm64      16kB
  + ld64_osx-arm64               609  h6ce2ded_10         conda-forge/osx-arm64       1MB
  + libclang-cpp13            13.0.1  default_h2cfa9b4_0  conda-forge/osx-arm64      13MB
  + libllvm13                 13.0.1  hfd59cb2_2          conda-forge/osx-arm64      24MB
  + llvm-tools                13.0.1  hfd59cb2_2          conda-forge/osx-arm64      12MB
  + logical-unification        0.4.5  pyhd8ed1ab_0        conda-forge/noarch         16kB
  + minikanren                 1.0.3  pyhd8ed1ab_0        conda-forge/noarch         24kB
  + multipledispatch           0.6.0  py_0                conda-forge/noarch         12kB
  + openblas                  0.3.20  openmp_h745f6c2_0   conda-forge/osx-arm64       4MB
  + pymc                       4.0.0  py39h3704c81_1      conda-forge/osx-arm64       9kB
  + pymc-base                  4.0.0  py39h2804cbe_1      conda-forge/osx-arm64     936kB
  + sigtool                    0.1.3  h7747421_0          conda-forge/osx-arm64     210kB
  + tapi                   1100.0.11  he4954df_0          conda-forge/osx-arm64     191kB
  + xarray                  2022.3.0  pyhd8ed1ab_0        conda-forge/noarch        666kB
  + xarray-einstats            0.2.2  pyhd8ed1ab_0        conda-forge/noarch         33kB

  Downgrade:
───────────────────────────────────────────────────────────────────────────────────────────

  - typing-extensions          4.2.0  hd8ed1ab_1          conda-forge                    
  + typing-extensions       3.10.0.2  hd8ed1ab_0          conda-forge/noarch          8kB
  - typing_extensions          4.2.0  pyha770c72_1        conda-forge                    
  + typing_extensions       3.10.0.2  pyha770c72_0        conda-forge/noarch         29kB

  Summary:

  Install: 33 packages
  Downgrade: 2 packages

  Total download: 70MB

───────────────────────────────────────────────────────────────────────────────────────────

```

**Pull request closed without merging**
