### PR TITLE
updated v2.7.10

### LINKED ISSUE #102: Aesara 2.7.8 and 2.7.9 are broken with setuptools<48.0.0
It seems likely that https://github.com/aesara-devs/aesara/pull/1100 will be merged soon. Subsequently we should fix the old broken versions.

See https://github.com/pymc-devs/pymc/issues/6013.

We should patch the repodata to retroactively fix this.

### PR DESCRIPTION
**Pull request by maresb**
Closes #102

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Please close any duplicates opened by autotick-bot since they won't contain the setuptools bump.

As far as I can tell, this is unrelated to the recent setuptools issue regarding the removal of `distutils.msvccompiler`.

**Comment by maresb** [comment]
I don't understand why this is breaking and I'm out of time at the moment. Hopefully I can have a look tomorrow.

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
I suspect this was https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/308. The timing lines up.

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@brandonwillard, thanks for the PR https://github.com/aesara-devs/aesara/pull/1131 to solve https://github.com/aesara-devs/aesara/issues/1129!

Shall we skip the conda-forge release of rel-2.7.10 and target rel-2.7.11 instead?

**Comment by brandonwillard** [comment]
> Shall we skip the conda-forge release of rel-2.7.10 and target rel-2.7.11 instead?

Yeah, that sounds good.

**Pull request closed without merging**
