### PR TITLE
Prevent breakage with NumPy 1.26

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Reference: https://github.com/aesara-devs/aesara/issues/1513

**Review by brandonwillard — APPROVED** [review]
I created a new release with a fix for this issue, but it's probably best to upper bound it until the test coverage matches the new NumPy version.

**Comment by maresb** [comment]
@brandonwillard shall I close this in favor of 2.9.2 and instead do a repodata patch to fix everything retroactively on conda-forge?

**Comment by brandonwillard** [comment]
> @brandonwillard shall I close this in favor of 2.9.2 and instead do a repodata patch to fix everything retroactively on conda-forge?

That would be cool.

**Comment by maresb** [comment]
To be specific add <1.26 to all numpy deps in previous versions

**Pull request closed without merging**
