### PR TITLE
[ci skip] adding user @maresb

### LINKED ISSUE #100: @conda-forge-admin, please add user @maresb
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've added user @maresb as instructed in #100.

Merge this PR to add the user. Please do not rerender this PR or change it in any way. It has `[ci skip]` in the commit message to avoid pushing a new build and so the build configuration in the feedstock should not be changed.

Please contact [conda-forge/core](https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-contact-core) to have this PR merged, if the maintainer is unresponsive.

Fixes #100

### CODE REVIEW

**Review by brandonwillard — APPROVED** [review]

**Comment by maresb** [comment]
Thanks @brandonwillard! This will certainly make life easier, e.g. so that I can commit directly to the PRs of the autotick-bot.

**Comment by brandonwillard** [comment]
> Thanks @brandonwillard! This will certainly make life easier, e.g. so that I can commit directly to the PRs of the autotick-bot.

No problem; thanks for improving our conda build situation!

**Comment by maresb** [comment]
The `[ci skip]` flag is broken. (Known Conda-Forge issue these days.) This is safe to merge without being green.

**Comment by maresb** [comment]
(Or just label as `automerge` if that hurts morally. :wink:)

**Pull request merged**
