### PR TITLE
Add build for linux-aarch64

### PR DESCRIPTION
**Pull request by jeffreyenos**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jeffreyenos** [comment]
@conda-forge-admin, please rerender

**Comment by jeffreyenos** [comment]
@conda-forge-admin, please rerender

**Review by brandonwillard — COMMENTED** [review]
Looks like the `import aesara` issue only appears in the aarch pypy builds.  

The other issue appears to be [a Windows-specific test script bug](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=670742&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1e3b5e03-2b58-5acf-49d8-7964b3450f7e&l=12).

**Comment by jeffreyenos** [comment]
> Looks like the `import aesara` issue only appears in the aarch pypy builds.

I'm not sure what's causing this. I'll start by looking for differences in the test environments for `linux_aarch64_python3.8.____73_pypy` and `linux_aarch64_python3.8.____cpython` using `conda debug`.

> 
> The other issue appears to be [a Windows-specific test script bug](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=670742&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1e3b5e03-2b58-5acf-49d8-7964b3450f7e&l=12).

Looks like this has been addressed in https://github.com/conda-forge/conda-smithy/pull/1724 and so should be fixed in the next release of `conda-smithy`.

**Comment by jeffreyenos** [comment]
I noticed in the logs for the build process that only [1 file was being bundled](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=671493&view=logs&j=3a25022a-f08c-5c04-be7d-d279a7fc48ef&t=03fcd6e6-009d-576b-db27-27f5032302f9&l=319) during post-processing.

In the pypy build the problem seems to be related to `pip` installing Aesara in the wrong place.

There are two environments activated before Aesara is installed in `output_script.sh`, e.g.:

```bash
eval "$('/opt/conda/bin/python3.10' -m conda shell.bash hook)"
conda activate "/home/conda/feedstock_root/build_artifacts/aesara-suite_1678654328814/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol"
conda activate --stack "/home/conda/feedstock_root/build_artifacts/aesara-suite_1678654328814/_build_env"

python -m pip install . --no-deps -vv
```

The environment variables `PREFIX` and `BUILD_PREFIX` correspond to the first and second environments above, respectively:

```
PREFIX=/home/conda/feedstock_root/build_artifacts/aesara-suite_1678654328814/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
BUILD_PREFIX=/home/conda/feedstock_root/build_artifacts/aesara-suite_1678654328814/_build_env
```

In the cpython aarch64 builds, Aesara is installed to `PREFIX`, while in the pypy aarch64 builds it's installed to `BUILD_PREFIX`, and is subsequently ignored during bundling. I'm not sure why this is happening, but I was able to fix the issue by explicitly setting `--prefix ${PREFIX}` when running `pip`.

Of course, this breaks the Windows builds.

**Comment by brandonwillard** [comment]
> In the cpython aarch64 builds, Aesara is installed to `PREFIX`, while in the pypy aarch64 builds it's installed to `BUILD_PREFIX`, and is subsequently ignored during bundling. I'm not sure why this is happening, but I was able to fix the issue by explicitly setting `--prefix ${PREFIX}` when running `pip`.

That's a great find!  I'll take a look at it from the Aesara side; there might be some special platform-specific handling involved.

**Comment by maresb** [comment]
Very nicely done, @jeffreyenos! 

Do you have an explanation for 78c7b82? Namely, is this a conda-forge bug, and if so, has it been reported? (I'm mainly wondering if we'll have to revert this file each time we rerender.)

**Comment by jeffreyenos** [comment]
> Very nicely done, @jeffreyenos!

Thank you!

> 
> Do you have an explanation for [78c7b82](https://github.com/conda-forge/aesara-feedstock/commit/78c7b82e4c8557344d55cf84f782c3447dbc04ce)? Namely, is this a conda-forge bug, and if so, has it been reported? (I'm mainly wondering if we'll have to revert this file each time we rerender.)

The batch file issue should be fixed in the next release of `conda-smithy` (see https://github.com/conda-forge/aesara-feedstock/pull/127#issuecomment-1465051416) so going forward shouldn't be an issue.

**Comment by maresb** [comment]
Thanks so much for the contribution @jeffreyenos! (Sorry I didn't properly read your previous comment.)

**Comment by jeffreyenos** [comment]
> Thanks so much for the contribution @jeffreyenos! (Sorry I didn't properly read your previous comment.)

No worries of course -- thanks for merging!

**Pull request merged**
